var comments = {
    elements: {
        lengths: {
            username: {
                min:<?php echo $fieldMinLength['username'] ?>,
                max:<?php echo $fieldMaxLength['username'] ?>
            },
            email: {
                min:<?php echo $fieldMinLength['email'] ?>,
                max:<?php echo $fieldMaxLength['email'] ?>
            },
            text: {
                min:<?php echo $fieldMinLength['text'] ?>,
                max:<?php echo $fieldMaxLength['text'] ?>
            }
        }
    }
};